version: "3.3"
services:
  spring:
    build: 
      context: spring
      dockerfile: Dockerfile
    networks:
      - backend
      - frontend

  vue:
    build:
      context: vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring
    networks:
      - frontend

networks:
  backend:
  frontend:
