# Node.js with Vue

# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (77b9c588-ea9e-44b2-a21f-dc859f7e5f73)'
    appType: 'webAppLinux'
    WebAppName: 'bankplusplus-vue'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'STATICSITE|1.0'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: vue/
